### ISSUE TITLE
uses babel 2.4.0

### ISSUE THREAD

**Issue by akhilrajvc** [vimeo/py-money#7]
its forcing me to use babel 2.4.0 even if i already installed latest version of babel(2.6.0)

**Comment by nickyr** [comment]
Think this will do the trick? https://github.com/vimeo/py-money/pull/8

I'm bad at pypi :-)

**Comment by nickyr** [comment]
This has been released as 0.4.0. LMK if you have any issues, I'm terrible at PyPi.
